-- Berlayar Rise tracker schema reference / bootstrap.
-- Scope: riseblock only. No DROP SCHEMA / cross-schema statements are included.
-- This file is for a fresh setup. The live project already has these objects.

create schema if not exists riseblock;

create table if not exists riseblock.projects (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  town text not null,
  launch text not null,
  classification text,
  total_units integer not null check (total_units > 0),
  created_at timestamptz not null default now()
);

create table if not exists riseblock.blocks (
  id bigint generated by default as identity primary key,
  project_id bigint not null references riseblock.projects(id) on delete cascade,
  block_code text not null unique,
  storeys integer not null check (storeys > 0),
  total_units integer not null check (total_units > 0),
  wait_months integer,
  min_residential_floor integer not null,
  max_residential_floor integer not null,
  terrace_levels integer[] not null default '{}',
  roof_garden boolean not null default false,
  ground_amenities text[] not null default '{}',
  source_ref text,
  created_at timestamptz not null default now(),
  check (max_residential_floor >= min_residential_floor)
);

create table if not exists riseblock.stacks (
  id bigint generated by default as identity primary key,
  block_id bigint not null references riseblock.blocks(id) on delete cascade,
  stack_no text not null,
  flat_type text not null check (flat_type in ('2R-T1','2R-T2','3R','4R')),
  sort_order integer not null check (sort_order > 0),
  source_ref text,
  unique (block_id, stack_no),
  unique (block_id, sort_order)
);

create table if not exists riseblock.units (
  id bigint generated by default as identity primary key,
  block_id bigint not null references riseblock.blocks(id) on delete cascade,
  stack_id bigint not null references riseblock.stacks(id) on delete cascade,
  floor integer not null check (floor > 0),
  stack_no text not null,
  unit_no text not null,
  flat_type text not null check (flat_type in ('2R-T1','2R-T2','3R','4R')),
  area_sqm integer not null check (area_sqm > 0),
  internal_area_sqm integer not null check (internal_area_sqm > 0),
  price_min integer not null check (price_min > 0),
  price_max integer not null check (price_max >= price_min),
  source_ref text,
  created_at timestamptz not null default now(),
  unique (block_id, floor, stack_no),
  unique (block_id, unit_no)
);

create table if not exists riseblock.unit_reports (
  id bigint generated by default as identity primary key,
  unit_id bigint not null references riseblock.units(id) on delete cascade,
  reported_status text not null check (reported_status in ('available','taken')),
  observed_at timestamptz not null,
  source_type text not null check (source_type in ('hdb_selection','community_observation','other')),
  source_note text,
  evidence_url text,
  reporter_token uuid not null,
  moderation_status text not null default 'active' check (moderation_status in ('active','rejected')),
  created_at timestamptz not null default now(),
  check (char_length(coalesce(source_note,'')) <= 500),
  check (char_length(coalesce(evidence_url,'')) <= 1000)
);

create table if not exists riseblock.block_quota_reports (
  id bigint generated by default as identity primary key,
  block_id bigint not null references riseblock.blocks(id) on delete cascade,
  malay_remaining integer not null check (malay_remaining >= 0),
  chinese_remaining integer not null check (chinese_remaining >= 0),
  indian_other_remaining integer not null check (indian_other_remaining >= 0),
  observed_at timestamptz not null,
  source_type text not null check (source_type in ('hdb_selection','community_observation','other')),
  source_note text,
  evidence_url text,
  reporter_token uuid not null,
  moderation_status text not null default 'active' check (moderation_status in ('active','rejected')),
  created_at timestamptz not null default now(),
  check (char_length(coalesce(source_note,'')) <= 500),
  check (char_length(coalesce(evidence_url,'')) <= 1000)
);

create table if not exists riseblock.selection_progress_reports (
  id bigint generated by default as identity primary key,
  queue_reached integer not null check (queue_reached >= 0),
  dropouts integer not null check (dropouts >= 0 and dropouts <= queue_reached),
  observed_at timestamptz not null,
  source_type text not null check (source_type in ('hdb_selection','community_observation','appointment_group','other')),
  source_note text,
  evidence_url text,
  reporter_token uuid not null,
  moderation_status text not null default 'active' check (moderation_status in ('active','rejected')),
  created_at timestamptz not null default now(),
  check (char_length(coalesce(source_note,'')) <= 500),
  check (char_length(coalesce(evidence_url,'')) <= 1000)
);

create index if not exists unit_reports_unit_observed_idx on riseblock.unit_reports (unit_id, observed_at desc);
create index if not exists unit_reports_reporter_created_idx on riseblock.unit_reports (reporter_token, created_at desc);
create index if not exists quota_reports_block_observed_idx on riseblock.block_quota_reports (block_id, observed_at desc);
create index if not exists quota_reports_reporter_created_idx on riseblock.block_quota_reports (reporter_token, created_at desc);
create index if not exists progress_reports_observed_idx on riseblock.selection_progress_reports (observed_at desc);
create index if not exists progress_reports_reporter_created_idx on riseblock.selection_progress_reports (reporter_token, created_at desc);

alter table riseblock.projects enable row level security;
alter table riseblock.blocks enable row level security;
alter table riseblock.stacks enable row level security;
alter table riseblock.units enable row level security;
alter table riseblock.unit_reports enable row level security;
alter table riseblock.block_quota_reports enable row level security;
alter table riseblock.selection_progress_reports enable row level security;

drop policy if exists projects_public_read on riseblock.projects;
create policy projects_public_read on riseblock.projects for select to anon, authenticated using (true);
drop policy if exists blocks_public_read on riseblock.blocks;
create policy blocks_public_read on riseblock.blocks for select to anon, authenticated using (true);
drop policy if exists stacks_public_read on riseblock.stacks;
create policy stacks_public_read on riseblock.stacks for select to anon, authenticated using (true);
drop policy if exists units_public_read on riseblock.units;
create policy units_public_read on riseblock.units for select to anon, authenticated using (true);

grant usage on schema riseblock to anon, authenticated;
grant select on riseblock.projects, riseblock.blocks, riseblock.stacks, riseblock.units to anon, authenticated;

-- Raw report tables intentionally have no public SELECT/INSERT/UPDATE/DELETE policy.
-- Community writes go through the three controlled submit_* RPC functions in the live schema.
